import { supabase } from "../api/supabase";

/**
 * Starring a work item (M21).
 *
 * Backed by `todo_stars`, added in `20260821140000_create_todo_stars.sql` — the
 * one fact the For You page could not derive from existing columns. That
 * migration's header records why a table, and why this one rather than an array
 * column or a general flags table.
 *
 * **Self-only by RLS, which is stricter than the rest of the schema and meant
 * to be.** Everything else here is visible to board members; a star is a
 * private annotation, and a board mate has no business reading which cards you
 * flagged for yourself.
 *
 *
 * ## The cast, and how to delete it
 *
 * `src/types/database.ts` is generated by `npm run db:types` **against the
 * linked project**, so it does not know about `todo_stars` until the migration
 * has actually been applied there. Until then `supabase.from("todo_stars")` is
 * a type error — the table is not in the generated union — and this file would
 * not compile.
 *
 * So there is exactly one cast, here, at the boundary, wrapped in one function
 * so nothing else in the codebase has to know about it. **After running:**
 *
 *     npm run db:push
 *     npm run db:types
 *
 * delete `starsTable()` and call `supabase.from("todo_stars")` directly; the
 * three callers below need no other change. The row shape is declared
 * explicitly rather than inferred, so the compiler is still checking the
 * columns this file reads — the cast buys past the table's *existence*, not
 * past its shape.
 */

/** What the table holds. Mirrors the migration; three columns, no surrogate id. */
interface TodoStarRow {
  user_id: string;
  todo_id: string;
  created_at: string;
}

/**
 * PostgREST's code for "relation does not exist".
 *
 * The migration ships in the same commit as this client but is applied by hand,
 * so there is a real window where the code is deployed and the table is not.
 * Treating that as an ordinary failure would put a red error toast on a tab the
 * user merely visited; naming it lets the Starred tab explain itself instead.
 */
const UNDEFINED_TABLE = "42P01";

export class StarsNotMigratedError extends Error {
  constructor() {
    super(
      "Starring needs migration 20260821140000 — run `npm run db:push`, then `npm run db:types`.",
    );
    this.name = "StarsNotMigratedError";
  }
}

function starsTable() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (supabase as any).from("todo_stars");
}

/** True when this error is the missing table rather than a real failure. */
function isMissingTable(error: { code?: string } | null): boolean {
  return error?.code === UNDEFINED_TABLE;
}

/**
 * One person's stars, newest first.
 *
 * Ids and instants only — the rows come from `fetchTodosByIds`, so a star on a
 * board the caller has since been removed from resolves to nothing and quietly
 * disappears from the tab. No client-side access check is needed or wanted;
 * `todos` RLS is the one that decides.
 */
export async function fetchStars(
  userId: string,
): Promise<Map<string, string>> {
  const { data, error } = await starsTable()
    .select("todo_id, created_at")
    .eq("user_id", userId)
    .order("created_at", { ascending: false });

  if (error) {
    if (isMissingTable(error)) throw new StarsNotMigratedError();

    throw error;
  }

  const stars = new Map<string, string>();

  for (const row of (data ?? []) as Pick<
    TodoStarRow,
    "todo_id" | "created_at"
  >[]) {
    stars.set(row.todo_id, row.created_at);
  }

  return stars;
}

/**
 * Star one work item.
 *
 * An upsert, so pressing star on something already starred is a no-op rather
 * than a duplicate-key error — the pair is the primary key, which is what makes
 * that safe. `created_at` is left to the column default so the *first* star's
 * time is kept rather than being refreshed by a repeat press.
 */
export async function addStar(userId: string, todoId: string) {
  const { error } = await starsTable().upsert(
    { user_id: userId, todo_id: todoId },
    { onConflict: "user_id,todo_id", ignoreDuplicates: true },
  );

  if (error) {
    if (isMissingTable(error)) throw new StarsNotMigratedError();

    throw error;
  }
}

/** Unstar. Both halves of the key, because the policy only checks the user. */
export async function removeStar(userId: string, todoId: string) {
  const { error } = await starsTable()
    .delete()
    .eq("user_id", userId)
    .eq("todo_id", todoId);

  if (error) {
    if (isMissingTable(error)) throw new StarsNotMigratedError();

    throw error;
  }
}
