import type { Database } from "./database";

/** Shorthand for a generated table row — `Row<"todos">` etc. */
type Row<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

/**
 * These three are derived from `database.ts`, which is generated by
 * `npm run db:types`. Do not hand-edit their fields: if one looks wrong, the
 * schema is wrong, and the fix is a migration followed by regeneration.
 *
 * Nullability here is the database's, not the application's wish. `title`,
 * `position`, `column_id` and `category` are all nullable columns, which is
 * why `categoryOf()` takes `string | null` and the sorts guard their inputs.
 * Most of these nulls are invisible today because `strictNullChecks` is off;
 * they become real once M0-09 lands.
 */
export type ISupabaseTodo = Row<"todos"> & {
  /** Client-only: set on a card the server has not confirmed yet. */
  isOptimistic?: boolean;
};

export type ISupabaseProfile = Row<"profiles">;

export type IColumn = Row<"columns">;

export interface TodoItemProps extends ISupabaseTodo {
  overlay?: boolean;
  menuOpen: boolean;
  // currentColumnId: string;
  closeMenu: () => void;
  openMenu: () => void;
}
export interface TodoMenuProps {
  menuOpen: boolean;

  openMenu?: () => void;

  closeMenu?: () => void;

  onEdit?: () => void;

  todoId: number;

  // currentColumnId: string;
}
