import type { Database } from "./database";

/** Shorthand for a generated table row — `Row<"todos">` etc. */
type Row<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

/**
 * These three are derived from `database.ts`, which is generated by
 * `npm run db:types`. Do not hand-edit their fields: if one looks wrong, the
 * schema is wrong, and the fix is a migration followed by regeneration.
 *
 * Nullability here is the database's, not the application's wish. `title`,
 * `position`, `column_id` and `category` are all nullable columns, which is
 * why `categoryOf()` takes `string | null` and the sorts guard their inputs.
 * Most of these nulls are invisible today because `strictNullChecks` is off;
 * they become real once M0-09 lands.
 */
/**
 * No client-only fields. There used to be an `isOptimistic` flag, needed only
 * because an optimistic row carried a fake `Date.now()` id that had to be told
 * apart from a real one. Since M2-14 the client mints the row's real uuid, so
 * the optimistic row *is* the row — there is nothing to distinguish.
 */
/**
 * A complete `todos` row.
 *
 * Rarely what you want. The board and the list never hold one — they hold
 * `Todo`, the projection below. This exists for the detail view (M5-06), which
 * is the only screen that renders `description`, and for anything that needs a
 * column the board does not fetch.
 */
export type TodoRow = Row<"todos">;

/**
 * A work item as the board holds it: the twelve columns the UI actually uses.
 *
 * **The board query does not `select("*")` (M5-07)**, so this is not a
 * convenience narrowing — it is what the cache genuinely contains. Typing it as
 * the full row would be a lie the compiler enforces: `todo.description` would
 * type-check and be `undefined` at runtime, and the first screen to read it
 * would fail silently rather than at the query.
 *
 * Five columns are deliberately absent. `description` is the one the plan
 * names — fetched for every card on every board load and rendered by nothing.
 * `archived`, `creator_id`, `status` and `previous_status` join it:
 * `status`/`previous_status` are dead columns kept by the schema (doneness is
 * the column's category, never a field), and neither `archived` nor
 * `creator_id` has a reader anywhere in the app.
 *
 * `estimate` was the sixth until M24 (2026-08-26) gave it a meaning — story
 * points — and a reader. It is in `TODO_FIELDS` now for the same reason
 * `priority` is: a control that can set it needs the board's own cache to
 * hold the value it just wrote, not just the detail panel's `select("*")`.
 *
 * **This is the row shape every view reads** (M16) — the board, the list, and
 * the date-based views when they arrive. Widening it for a new view happens
 * here, once, rather than per view.
 *
 * `TODO_FIELDS` is the field list and `Todo` is a `Pick` over it, so the two
 * cannot disagree. `satisfies readonly (keyof TodoRow)[]` makes a typo a
 * compile error rather than a column PostgREST rejects at runtime.
 *
 * It could not be merged with `TODO_LIST_FIELDS` in `todos/todoApi.ts`, which
 * would have been the tidier answer: `supabase-js` infers the returned row from
 * the select's *literal* type, and a derived string collapses every query
 * result to `GenericStringError[]`. They stay two constants, and
 * `todoApi.test.ts` asserts they agree — which is the part that used to be a
 * comment asking you to remember.
 */
export const TODO_FIELDS = [
  "id",
  "board_id",
  "column_id",
  "position",
  // Both orderings, deliberately, for the length of M6-A. `rank` is what the
  // app orders by (M6-03); `position` is still written by the insert path and
  // is the rollback, which is exactly why M6-05 — dropping it — is a separate
  // migration after a soak rather than part of this one.
  "rank",
  "board_key",
  "title",
  "type",
  "priority",
  // Both ends of the range, and they arrive together (M20). The plan named
  // `start_date` at M16 for exactly this moment: "adding `start_date` for M20
  // widens it once, here, rather than per view" — so the Timeline is a
  // renderer over the row every view already holds, not a query of its own.
  //
  // Same type and same convention as `due_date`: a `timestamptz` holding
  // midnight UTC, read back through `toCalendarDay`. See the migration
  // `20260817090000_todos_start_date.sql` for why the plan's `date` was not
  // followed to the letter.
  "start_date",
  "due_date",
  "assignee_id",
  // Story points (M24). `null` means unestimated, not zero — see
  // `20260826090000_todos_estimate_check.sql` for the constraint that keeps
  // the column from meaning "points or hours" depending on who filled it in.
  "estimate",
  "created_at",
  "updated_at",
] as const satisfies readonly (keyof TodoRow)[];

export type Todo = Pick<TodoRow, (typeof TODO_FIELDS)[number]>;

/**
 * One entry in a board's history (M18).
 *
 * Trigger-written and read-only from the client — there is no insert grant on
 * the table, so nothing in the app can construct one of these and send it. The
 * shape is M7-05's, unchanged.
 *
 * `entity_type` and `action` are plain `text` with a CHECK over the *pair*
 * rather than enums, so the generated type is `string` on both. The union that
 * matters is applied where it is read, in `activities/activityText.ts`.
 */
export type Activity = Row<"activities">;

/**
 * One comment on one work item (M7-01).
 *
 * The whole row, unlike `Todo`: the table has seven columns and the thread
 * renders every one of them or uses it as a key, so there is nothing to narrow.
 *
 * `board_id` is on it because the policy needs it, not because a reader does —
 * it is denormalised from the work item and pinned there by a composite foreign
 * key, so it can never say anything the `todo_id` does not already imply.
 *
 * No client-only fields, for the reason `Todo` records: the client mints the
 * uuid, so an optimistic comment *is* the comment and there is nothing to tell
 * apart. What a reader wants — "has this been edited?" — is
 * `updated_at > created_at`, stamped by a trigger rather than claimed by us.
 */
export type Comment = Row<"comments">;

export type ISupabaseProfile = Row<"profiles">;

export type IColumn = Row<"columns">;

export type IBoard = Row<"boards">;

/**
 * A folder for boards (M15).
 *
 * Owner-only by RLS and **not a permission scope** — filing a board into a
 * space grants nobody access to it. A board you are a member of but whose space
 * belongs to someone else reads as unfiled, because that space row is not
 * returned to you at all.
 */
export type ISpace = Row<"spaces">;

/**
 * Client-only state about a todo that no column of `todos` holds.
 *
 * Separate from `Todo` rather than optional fields on it, which is the mistake
 * this milestone exists to undo: `isOptimistic?` used to live inside the row
 * type, so a database row and a UI concern shared one shape and neither could
 * be reasoned about alone. M2-14 removed that flag; this is where its
 * successors go instead.
 */
export interface TodoViewState {
  /** This card is the one under the cursor — the board dims it in place. */
  dragging?: boolean;
  /** This is the DragOverlay's copy, not the card in the column. */
  overlay?: boolean;
  /**
   * Whether this card may be picked up.
   *
   * A drop means "put it here", and "here" is only answerable while the board is
   * showing stored order in its own columns. Under a view sort or a swimlane it
   * is not, so the card says so by not moving. See `useBoardView.dndDisabled`.
   */
  dragDisabled?: boolean;
}

/**
 * The stored values a card puts on screen, and nothing else.
 *
 * **Deliberately not `extends Todo`.** The card used to take a whole database
 * row as its props — every consumer spread one in — so a column added to
 * `todos` became a props change in a leaf component, and the card could not be
 * rendered at all without a real row to hand it. This lists the four fields it
 * actually reads, so it can be constructed by hand, and a schema change reaches
 * it only through `toCardContent`.
 *
 * `id`, `boardId` and `columnId` were here in M5-01 because the card wrote
 * through `useTodoPatch` and registered its own draggable. M5-02 moved both to
 * `TodoItem`, so none of the three is content and none of them is here.
 */
export interface TodoCardContent {
  title: string | null;
  /**
   * The rendered key — `KAN-12` — not its two halves.
   *
   * It was `boardKey: number` until M14 made the prefix a board setting. The
   * card composed `KAN-{boardKey}` from a literal back then, which is a
   * presentational component holding a fact about the board it is not given.
   * Assembling it in `toCardContent` keeps the card rendering one value and
   * keeps the prefix's only reader on the board side of the boundary.
   *
   * Null while the insert is in flight, as `boardKey` was: `board_key` is
   * assigned by a trigger, so an optimistic row has no key yet.
   */
  taskKey: string | null;
  workType: string | null;
  /**
   * Added by M17's second pass. `todos.priority` has been on the row since
   * M2-04 and had a control since M5, but the card never showed it — so the
   * one field that says *how urgent* a card is was the one field you had to
   * open the card to see.
   */
  priority: string | null;
  dueDate: string | null;
}
