import type { Database } from "./database";

/** Shorthand for a generated table row — `Row<"todos">` etc. */
type Row<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

/**
 * These three are derived from `database.ts`, which is generated by
 * `npm run db:types`. Do not hand-edit their fields: if one looks wrong, the
 * schema is wrong, and the fix is a migration followed by regeneration.
 *
 * Nullability here is the database's, not the application's wish. `title`,
 * `position`, `column_id` and `category` are all nullable columns, which is
 * why `categoryOf()` takes `string | null` and the sorts guard their inputs.
 * Most of these nulls are invisible today because `strictNullChecks` is off;
 * they become real once M0-09 lands.
 */
/**
 * No client-only fields. There used to be an `isOptimistic` flag, needed only
 * because an optimistic row carried a fake `Date.now()` id that had to be told
 * apart from a real one. Since M2-14 the client mints the row's real uuid, so
 * the optimistic row *is* the row — there is nothing to distinguish.
 */
export type ISupabaseTodo = Row<"todos">;

export type ISupabaseProfile = Row<"profiles">;

export type IColumn = Row<"columns">;

export type IBoard = Row<"boards">;

export interface TodoItemProps extends ISupabaseTodo {
  overlay?: boolean;
  /**
   * Whether this card may be picked up.
   *
   * A drop means "put it here", and "here" is only answerable while the board is
   * showing stored order in its own columns. Under a view sort or a swimlane it
   * is not, so the card says so by not moving. See `useBoardView.dndDisabled`.
   */
  dragDisabled?: boolean;
}
