import { supabase } from "@/services/api/supabase";
import type { IBoard } from "@/types/data";

/**
 * The fields a board's owner may edit. `owner_id` is deliberately absent.
 *
 * `space_id` is here as of M15 — moving a board between folders is an ordinary
 * patch, not its own endpoint. What it is **not** is unrestricted: the
 * `boards_space_ownership` trigger refuses a filing by anyone but the board's
 * owner, and refuses any space the caller does not own. Neither `key_prefix`
 * nor `next_key` is patchable, which is what makes a move incapable of
 * renumbering or relabelling a single card.
 */
type BoardPatch = Partial<
  Pick<
    IBoard,
    "title" | "description" | "icon" | "cover_color" | "visibility" | "space_id"
  >
>;

/**
 * Every board the current user can reach.
 *
 * No `.eq("owner_id", ...)` filter: RLS already scopes this to the caller, and
 * unlike the board-scoped queries in M2-11 there is no second dimension to
 * narrow by. When M3 makes boards shared, "mine" stops being the right set and
 * a client-side owner filter here would start hiding boards the user is a
 * member of — the policy widens, this query should not have to.
 */
export async function getBoards(): Promise<IBoard[]> {
  const { data, error } = await supabase
    .from("boards")
    .select("*")
    .order("created_at");

  if (error) throw error;

  return data;
}

/**
 * One board by id.
 *
 * `maybeSingle` rather than `single`, so a board that does not exist — or that
 * RLS hides, which is indistinguishable from the client — resolves to null
 * instead of throwing. M2-10 turns that null into a 404.
 */
export async function getBoard(id: string): Promise<IBoard | null> {
  const { data, error } = await supabase
    .from("boards")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) throw error;

  return data;
}

/**
 * `id` is generated by the caller, not the database.
 *
 * The column defaults to `gen_random_uuid()`, so this is a choice: it lets the
 * optimistic row carry the id the server will confirm, so the echo reconciles
 * by identity instead of by swapping a placeholder. The realtime handler in M6
 * needs the same property — an INSERT event arriving for a row already in the
 * cache has to be recognisable as the same row.
 *
 * `owner_id` is read from the session rather than accepted as an argument, so
 * a caller cannot create a board owned by somebody else. The RLS INSERT policy
 * rejects that anyway; this keeps it from being expressible.
 *
 * `boards.owner_id` has no `auth.uid()` default, so it has to be sent — the
 * defaulted `columns.user_id` that used to be the counter-example is gone as
 * of M2-13. Giving owner_id a default would let the client omit it entirely —
 * worth doing, but it is a schema change and belongs to its own task.
 */
export async function createBoard({
  id = crypto.randomUUID(),
  title,
  spaceId = null,
}: {
  id?: string;
  title: string;
  /**
   * Which space to file it into, or null for unfiled (M15). Created straight
   * into the space it was created from, rather than created loose and moved —
   * one write, and no window where a board the user made inside a folder is
   * sitting outside it.
   */
  spaceId?: string | null;
}): Promise<IBoard> {
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) throw new Error("Not authenticated");

  const { data, error } = await supabase
    .from("boards")
    .insert({ id, title, owner_id: user.id, space_id: spaceId })
    .select()
    .single();

  if (error) throw error;

  return data;
}

/** Rename, re-theme, or change visibility. */
export async function updateBoard({
  id,
  ...patch
}: { id: string } & BoardPatch): Promise<IBoard> {
  const { data, error } = await supabase
    .from("boards")
    .update(patch)
    .eq("id", id)
    .select()
    .single();

  if (error) throw error;

  return data;
}

/**
 * Deletes the board and, by the cascades M2-07 adds, its columns and todos.
 *
 * Nothing is rehomed first — deleting a board is meant to take its contents
 * with it, which is the opposite of `deleteColumn`. Returns the id so the
 * mutation can find the row it removed from the cache.
 */
export async function deleteBoard(id: string): Promise<{ id: string }> {
  const { error } = await supabase.from("boards").delete().eq("id", id);

  if (error) throw error;

  return { id };
}
