import { supabase } from "@/services/api/supabase";
import type { IBoard } from "@/types/data";

/** The fields a board's owner may edit. `owner_id` is deliberately absent. */
type BoardPatch = Partial<
  Pick<IBoard, "title" | "description" | "icon" | "cover_color" | "visibility">
>;

/**
 * Every board the current user can reach.
 *
 * No `.eq("owner_id", ...)` filter: RLS already scopes this to the caller, and
 * unlike the board-scoped queries in M2-11 there is no second dimension to
 * narrow by. When M3 makes boards shared, "mine" stops being the right set and
 * a client-side owner filter here would start hiding boards the user is a
 * member of — the policy widens, this query should not have to.
 */
export async function getBoards(): Promise<IBoard[]> {
  const { data, error } = await supabase
    .from("boards")
    .select("*")
    .order("created_at");

  if (error) throw error;

  return data;
}

/**
 * One board by id.
 *
 * `maybeSingle` rather than `single`, so a board that does not exist — or that
 * RLS hides, which is indistinguishable from the client — resolves to null
 * instead of throwing. M2-10 turns that null into a 404.
 */
export async function getBoard(id: string): Promise<IBoard | null> {
  const { data, error } = await supabase
    .from("boards")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) throw error;

  return data;
}

/**
 * `id` is generated by the caller, not the database.
 *
 * The column defaults to `gen_random_uuid()`, so this is a choice: it lets the
 * optimistic row carry the id the server will confirm, so the echo reconciles
 * by identity instead of by swapping a placeholder. The realtime handler in M6
 * needs the same property — an INSERT event arriving for a row already in the
 * cache has to be recognisable as the same row.
 *
 * `owner_id` is read from the session rather than accepted as an argument, so
 * a caller cannot create a board owned by somebody else. The RLS INSERT policy
 * rejects that anyway; this keeps it from being expressible.
 *
 * Unlike `columns.user_id`, `boards.owner_id` has no `auth.uid()` default, so
 * it has to be sent. Giving it one would let the client omit it entirely —
 * worth doing, but it is a schema change and belongs to its own task.
 */
export async function createBoard({
  id = crypto.randomUUID(),
  title,
}: {
  id?: string;
  title: string;
}): Promise<IBoard> {
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) throw new Error("Not authenticated");

  const { data, error } = await supabase
    .from("boards")
    .insert({ id, title, owner_id: user.id })
    .select()
    .single();

  if (error) throw error;

  return data;
}

/** Rename, re-theme, or change visibility. */
export async function updateBoard({
  id,
  ...patch
}: { id: string } & BoardPatch): Promise<IBoard> {
  const { data, error } = await supabase
    .from("boards")
    .update(patch)
    .eq("id", id)
    .select()
    .single();

  if (error) throw error;

  return data;
}

/**
 * Deletes the board and, by the cascades M2-07 adds, its columns and todos.
 *
 * Nothing is rehomed first — deleting a board is meant to take its contents
 * with it, which is the opposite of `deleteColumn`. Returns the id so the
 * mutation can find the row it removed from the cache.
 */
export async function deleteBoard(id: string): Promise<{ id: string }> {
  const { error } = await supabase.from("boards").delete().eq("id", id);

  if (error) throw error;

  return { id };
}
